version: '3'

services:
  # Eureka server
  discovery-server:
    container_name: discovery-server
    image: madchicken98/discovery-server
    ports:
      - "8761:8761"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: user-service
    container_name: user-service
    ports:
      - "3000:3000"
    networks:
      - my-network
    command: ["npm", "run", "dev"]
    depends_on:
      discovery-server:
        condition: service_healthy

networks:
  my-network:
    driver: bridge
